Fri May 20 19:45:20 CEST 2016 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Fri May 20 19:47:05 CEST 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-0154-cf45-84c8-00004485e692 
on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_77-b03
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
os.version=4.2.0-34-generic
derby.system.home=/home/jacopo/Desktop/git/web-proj/eatbit
Database Class Loader started - derby.database.classpath=''
Fri May 20 19:47:05 CEST 2016 Thread[DRDAConnThread_3,5,main] Cleanup action starting
java.sql.SQLException: Database 'users' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 20 19:47:05 CEST 2016 Thread[DRDAConnThread_3,5,main] (DATABASE = users), (DRDAID = {2}), Database 'users' not found.
----------------------------------------------------------------
Fri May 20 19:47:09 CEST 2016:
Shutting down instance a816c00e-0154-cf45-84c8-00004485e692 on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Fri May 20 19:47:09 CEST 2016 Thread[DRDAConnThread_3,5,main] (DATABASE = eatbitDB), (DRDAID = {3}), Database 'eatbitDB' shutdown.
----------------------------------------------------------------
Fri May 20 19:47:10 CEST 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 582f8014-0154-cf45-84c8-00004485e692 
on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_77-b03
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
os.version=4.2.0-34-generic
derby.system.home=/home/jacopo/Desktop/git/web-proj/eatbit
Database Class Loader started - derby.database.classpath=''
Fri May 20 19:48:05 CEST 2016 Thread[DRDAConnThread_5,5,main] Cleanup action starting
java.sql.SQLException: Database 'users' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 20 19:48:05 CEST 2016 Thread[DRDAConnThread_5,5,main] (DATABASE = users), (DRDAID = {6}), Database 'users' not found.
Fri May 20 19:48:05 CEST 2016 Thread[DRDAConnThread_4,5,main] (DATABASE = eatbitDB), (DRDAID = ��������.����-867504414455776748{5}), 
Fri May 20 19:48:05 CEST 2016 : 
org.apache.derby.iapi.error.ShutdownException: 
	at org.apache.derby.iapi.services.context.ContextManager.checkInterrupt(Unknown Source)
	at org.apache.derby.iapi.services.context.ContextManager.getContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getStatementContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getCurrentSQLSessionContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getDefaultSchema(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getCurrentSchemaName(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.getCurrentSchemaName(Unknown Source)
	at org.apache.derby.impl.drda.PiggyBackedSessionData.refresh(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.writePBSD(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Fri May 20 19:48:05 CEST 2016 Thread[DRDAConnThread_4,5,main] (DATABASE = eatbitDB), (DRDAID = ��������.����-867504414455776748{5}), Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = eatbitDB; diagnostic msg = 
Fri May 20 19:48:05 CEST 2016 : Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = eatbitDB; diagnostic msg = 
org.apache.derby.impl.drda.DRDAProtocolException: Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = eatbitDB; diagnostic msg = 
	at org.apache.derby.impl.drda.DRDAProtocolException.newAgentError(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.sendUnexpectedException(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.handleException(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Fri May 20 19:48:05 CEST 2016 : 
org.apache.derby.iapi.error.ShutdownException: 
	at org.apache.derby.iapi.services.context.ContextManager.checkInterrupt(Unknown Source)
	at org.apache.derby.iapi.services.context.ContextManager.getContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getStatementContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getCurrentSQLSessionContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getDefaultSchema(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getCurrentSchemaName(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.getCurrentSchemaName(Unknown Source)
	at org.apache.derby.impl.drda.PiggyBackedSessionData.refresh(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.writePBSD(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Fri May 20 19:48:05 CEST 2016 Thread[DRDAConnThread_4,5,main] (DATABASE = eatbitDB), (DRDAID = ��������.����-867504414455776748{5}), Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
Fri May 20 19:48:05 CEST 2016 : Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
java.sql.SQLException: Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.javaException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.rollback(Unknown Source)
	at org.apache.derby.impl.drda.Database.close(Unknown Source)
	at org.apache.derby.impl.drda.Session.close(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.closeSession(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.handleException(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ001: Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 13 more
Caused by: org.apache.derby.iapi.error.ShutdownException: 
	at org.apache.derby.iapi.services.context.ContextManager.checkInterrupt(Unknown Source)
	at org.apache.derby.iapi.services.context.ContextManager.getContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.getStatementContext(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.doRollback(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.userRollback(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.rollback(Unknown Source)
	... 6 more
Fri May 20 19:48:05 CEST 2016 Thread[DRDAConnThread_4,5,main] (DATABASE = eatbitDB), (DRDAID = ��������.����-867504414455776748{5}), Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = eatbitDB; diagnostic msg = Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
Fri May 20 19:48:05 CEST 2016 : Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = eatbitDB; diagnostic msg = Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
org.apache.derby.impl.drda.DRDAProtocolException: Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = eatbitDB; diagnostic msg = Java exception: ': org.apache.derby.iapi.error.ShutdownException'.
	at org.apache.derby.impl.drda.DRDAProtocolException.newAgentError(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.sendUnexpectedException(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.closeSession(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.handleException(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
----------------------------------------------------------------
Fri May 20 19:48:06 CEST 2016:
Shutting down instance 582f8014-0154-cf45-84c8-00004485e692 on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Fri May 20 19:48:06 CEST 2016 Thread[DRDAConnThread_5,5,main] (DATABASE = eatbitDB), (DRDAID = {7}), Database 'eatbitDB' shutdown.
----------------------------------------------------------------
Fri May 20 19:48:12 CEST 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 018f0039-0154-cf45-84c8-00004485e692 
on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_77-b03
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
os.version=4.2.0-34-generic
derby.system.home=/home/jacopo/Desktop/git/web-proj/eatbit
Database Class Loader started - derby.database.classpath=''
Fri May 20 19:49:04 CEST 2016 Thread[DRDAConnThread_5,5,main] Cleanup action starting
java.sql.SQLException: Database 'users' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 20 19:49:04 CEST 2016 Thread[DRDAConnThread_5,5,main] (DATABASE = users), (DRDAID = {11}), Database 'users' not found.
Fri May 20 19:49:47 CEST 2016 Thread[DRDAConnThread_5,5,main] Cleanup action starting
java.sql.SQLException: Database 'users' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 20 19:49:47 CEST 2016 Thread[DRDAConnThread_5,5,main] (DATABASE = users), (DRDAID = {12}), Database 'users' not found.
----------------------------------------------------------------
Fri May 20 19:49:48 CEST 2016:
Shutting down instance 018f0039-0154-cf45-84c8-00004485e692 on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Fri May 20 19:49:48 CEST 2016 Thread[DRDAConnThread_5,5,main] (DATABASE = eatbitDB), (DRDAID = {13}), Database 'eatbitDB' shutdown.
----------------------------------------------------------------
Fri May 20 19:50:12 CEST 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a666c073-0154-cf45-84c8-00004485e692 
on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_77-b03
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
os.version=4.2.0-34-generic
derby.system.home=/home/jacopo/Desktop/git/web-proj/eatbit
Database Class Loader started - derby.database.classpath=''
Fri May 20 19:50:13 CEST 2016 Thread[DRDAConnThread_3,5,main] Cleanup action starting
java.sql.SQLException: Database 'users' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 20 19:50:13 CEST 2016 Thread[DRDAConnThread_3,5,main] (DATABASE = users), (DRDAID = {15}), Database 'users' not found.
----------------------------------------------------------------
Fri May 20 19:50:15 CEST 2016:
Shutting down instance a666c073-0154-cf45-84c8-00004485e692 on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Fri May 20 19:50:15 CEST 2016 Thread[DRDAConnThread_3,5,main] (DATABASE = eatbitDB), (DRDAID = {16}), Database 'eatbitDB' shutdown.
----------------------------------------------------------------
Fri May 20 19:50:15 CEST 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 07170079-0154-cf45-84c8-00004485e692 
on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_77-b03
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
os.version=4.2.0-34-generic
derby.system.home=/home/jacopo/Desktop/git/web-proj/eatbit
Database Class Loader started - derby.database.classpath=''
Fri May 20 19:50:21 CEST 2016 Thread[DRDAConnThread_6,5,main] Cleanup action starting
java.sql.SQLException: Database 'users' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'users' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 20 19:50:21 CEST 2016 Thread[DRDAConnThread_6,5,main] (DATABASE = users), (DRDAID = {18}), Database 'users' not found.
----------------------------------------------------------------
Fri May 20 19:50:21 CEST 2016:
Shutting down instance 07170079-0154-cf45-84c8-00004485e692 on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Fri May 20 19:50:21 CEST 2016 Thread[DRDAConnThread_6,5,main] (DATABASE = eatbitDB), (DRDAID = {19}), Database 'eatbitDB' shutdown.
----------------------------------------------------------------
Fri May 20 19:50:27 CEST 2016:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance 88100081-0154-cf45-84c8-00004485e692 
on database directory /home/jacopo/Desktop/git/web-proj/eatbit/eatbitDB with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/usr/lib/jvm/java-8-oracle/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_77-b03
user.dir=/usr/lib/jvm/java-8-oracle/db
os.name=Linux
os.arch=amd64
os.version=4.2.0-34-generic
derby.system.home=/home/jacopo/Desktop/git/web-proj/eatbit
Database Class Loader started - derby.database.classpath=''
